version: "3.9"
services:
  nginx:
    build: ./nginx/
    container_name: nginx2
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html
  
  php:
    build: ./src/
    expose:
      - 9000

    volumes:
      - ./src/:/var/www/html

  db:
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql2-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=default_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    expose:
      - 3306

volumes:
  mysql2-data: